name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build APK using Buildozer Action
        uses: Artemis-Skade/buildozer-action@v1.2
        with:
          command: buildozer android debug
          buildozer_version: master

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DateCalculator-APK
          path: bin/*.apk
